ALTER TABLE public.books ADD COLUMN format text;
ALTER TABLE public.books ADD COLUMN tags text;
ALTER TABLE public.books ALTER COLUMN author_last DROP NOT NULL;
ALTER TABLE public.books ALTER COLUMN author_first DROP NOT NULL;


ALTER TABLE authors ADD COLUMN owner_id text;
ALTER TABLE public.authors DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.authors TO anon, authenticated, service_role;


INSERT INTO public.profiles (id, display_name) 
VALUES ('00000000-0000-0000-0000-000000000000', 'Annabelle')
ON CONFLICT (id) DO NOTHING;

-- 1. 让 books 表在收到没有或对不上的 owner_id 时，默认都算给 Annabelle
ALTER TABLE public.books ALTER COLUMN owner_id SET DEFAULT '00000000-0000-0000-0000-000000000000';

-- 2. 临时关闭外键约束（刷完数据再开），防止种子脚本里的旧 ID 捣乱
ALTER TABLE public.books DROP CONSTRAINT IF EXISTS books_owner_id_fkey;

CREATE TABLE IF NOT EXISTS public.authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first text,
    last text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 关闭这张表的权限限制，方便种子脚本写入
ALTER TABLE public.authors DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.book_authors (
    book_id bigint, -- 如果你的 books 表主键是 UUID 类型，请把 bigint 改为 uuid
    author_id bigint, -- 如果你的 authors 表主键是 UUID 类型，请把 bigint 改为 uuid
    PRIMARY KEY (book_id, author_id)
);

-- 关闭权限封印，允许种子脚本直接写入关系
ALTER TABLE public.book_authors DISABLE ROW LEVEL SECURITY;

alter table public.book_authors add column role  text


-- 将 public 模式下所有当前表的所有权限，赋予全部角色
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- 确保未来创建的表也默认拥有该权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO postgres, anon, authenticated, service_role;

-- 1. 删掉旧的 bigint 桥梁表
DROP TABLE IF EXISTS public.book_authors;

-- 2. 重新创建正确的、支持 UUID 的桥梁表
CREATE TABLE public.book_authors (
    book_id uuid NOT NULL,    -- 这里改成 uuid 啦！
    author_id bigint NOT NULL, -- 如果一会儿还报同样的错，就把这里也改成 uuid
    PRIMARY KEY (book_id, author_id)
);

-- 3. 顺手把刚刚的权限和安全关卡拉满，一路绿灯
ALTER TABLE public.book_authors DISABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE public.book_authors TO postgres, anon, authenticated, service_role;

